import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-color4">
        <nav className="flex justify-center gap-16 pt-8 text-color5 font-medium underline underline-offset-8 tracking-wider">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/settings">Settings</Link>
          <Link href="/create">Create Quiz</Link>
        </nav>
        <main className="flex flex-1 items-center justify-center m-12 rounded-2xl bg-color5">{children}</main>
      </body>
    </html>
  );
}
